/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.busqueda;

import java.io.File;
import javax.swing.JFrame;
import vista.VentanaPrincipal;

/**
 *
 * @author JoseAntonio
 */
public class BuscaArchivos extends JFrame {

    /**
     * Creates new form BuscaArchivos
     */
    private boolean soyInput = false, soyBD = false;
    private String[] directorioAux;
    private int indice;
    private VentanaPrincipal padre;
    private String ruta;

    public BuscaArchivos() {
        initComponents();
    }

    public BuscaArchivos(String ruta, String texto, VentanaPrincipal padre) {
        initComponents();
        this.ruta = ruta;
        this.padre = padre;
        if (texto.compareToIgnoreCase("input") == 0) {
            this.jLabel1.setText("Previous Input Networks Loaded");
            this.soyInput = true;
        } else {
            this.jLabel1.setText("Previous Biological Databases Loaded");
            this.soyBD = true;
        }
        this.setLocationRelativeTo(null);
        File f = new File(ruta);
        String[] contenidoDirectorio = f.list();
        this.directorioAux = contenidoDirectorio;
        for (int i = 0; i < contenidoDirectorio.length; i++) {
            contenidoDirectorio[i] = calcularNombre(contenidoDirectorio[i]);
        }
        
        ListModelBuscaArchivos modelo = new ListModelBuscaArchivos(contenidoDirectorio);
        this.jList1.setModel(modelo);
        this.setTitle("GNC - Opening Files");
    }

    private String calcularNombre(String ruta) {
        int ultIndiceBarra = ruta.lastIndexOf(System.getProperty("file.separator"));
        int ultIndicePunto = ruta.lastIndexOf(".");
        String input = ruta.substring(ultIndiceBarra + 1, ultIndicePunto);
        return input;
    }

    public String[] getDirectorioAux() {
        return directorioAux;
    }

    public void setDirectorioAux(String[] directorioAux) {
        this.directorioAux = directorioAux;
    }

    public int getIndice() {
        return indice;
    }

    public void setIndice(int indice) {
        this.indice = indice;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        SelectB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setSelectedIndex(0);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        SelectB.setText("Load");
        SelectB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 267, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SelectB, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SelectB)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SelectBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectBActionPerformed
        if (soyBD) {
            this.padre.cambiarRutaBD(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
            this.padre.setRutaFicheroDB(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
            this.padre.setBbddSeleccionada(true);
        } else if (soyInput) {
            this.padre.cambiarRutaInput(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
            this.padre.setRutaFicheroInput(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
            this.padre.setInputSeleccionada(true);
        }
        this.dispose();
    }//GEN-LAST:event_SelectBActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        if (evt.getClickCount() == 2) {
            if (soyBD) {
                this.padre.cambiarRutaBD(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
                this.padre.setRutaFicheroDB(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
                this.padre.setBbddSeleccionada(true);
            } else if (soyInput) {
                this.padre.cambiarRutaInput(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
                this.padre.setRutaFicheroInput(this.ruta + System.getProperty("file.separator") + this.directorioAux[(this.jList1.getSelectedIndex())] + ".txt");
                this.padre.setInputSeleccionada(true);
            }
            this.dispose();
        }
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        this.setIndice(this.jList1.getSelectedIndex());
    }//GEN-LAST:event_jList1ValueChanged
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SelectB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
